### ISSUE TITLE
Date pickers overlaid on content

### ISSUE THREAD

**Issue by AndrewKLeech** [AndrewKLeech/GCTEAMC#26]
the date pickers in the reservation page are hard to use since they are overlaid on the existing page contend with no background. 
![image](https://cloud.githubusercontent.com/assets/11174630/25778562/a1ed5f04-333c-11e7-9054-3e8032ea5bc2.png)

**Comment by Jeongnny** [comment]
I edited code in the reservation_body.jsp to solve this problem!
